// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRUAaFkQG5r-ces5yrOIDqvGxlOvi0II',
    appId: '1:138519468481:web:8b517f2aac1da7f472b740',
    messagingSenderId: '138519468481',
    projectId: 'ztestonline',
    authDomain: 'ztestonline.firebaseapp.com',
    storageBucket: 'ztestonline.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwY0IqPR-ZeSFotb69_gHQ2G9CIXMBsrI',
    appId: '1:138519468481:android:d4a4850a806b73a172b740',
    messagingSenderId: '138519468481',
    projectId: 'ztestonline',
    storageBucket: 'ztestonline.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnRUAaFkQG5r-ces5yrOIDqvGxlOvi0II',
    appId: '1:138519468481:web:e7ebdc532d8361ca72b740',
    messagingSenderId: '138519468481',
    projectId: 'ztestonline',
    authDomain: 'ztestonline.firebaseapp.com',
    storageBucket: 'ztestonline.firebasestorage.app',
  );

}